language: go
go: 1.13
before_install: go get github.com/mattn/goveralls
install: go get -t ./...
script:
  - make test
  - make cover
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
