clone_folder: c:\gopath\src\github.com\nepcal\nepcal

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

test_script:
  - go test -v ./...
